### ISSUE TITLE
Cannot import user module

### ISSUE THREAD

**Issue by tangorboyz** [radish-bdd/radish#184]
I defined a function named `wait_for_element` in `__init__.py` in module util.
However when i import from a file `step_signup.py` in radish folder, it raise ModuleNotFoundError
Here's my folder structure
```

features
├── environment.py
├── signup.feature
└── steps
    └── step_signup.py
radish
├── step_signup.py
└── terrain.py
util
└── __init__.py
```

I import it with:
`from util import wait_for_element`

It worked for me with behave, but not radish.

**Comment by timofurrer** [comment]
Thanks for the report.

The problem here is that the local `util` package isn't part of your
import path. Simplified this means, that it's neither in `sys.path` nor
in `PYTHONPATH`.

I'm not sure about behave but they probably add the current directory to
the `sys.path` and that's why it was working with behave but not with
radish.

To make it work just set the `PYTHONPATH` env variable to the `cwd`:

```
PYTHONPATH=. radish features/signup.feature
```

Can you verify this? If needed I can upload an example.


On Sun, Oct 29, 2017 at 02:27:19PM +0000, Vincent Dhawu wrote:
> I defined a function named `wait_for_element` in `__init__.py` in module util.
> However when i import from a file `step_signup.py` in radish folder, it raise ModuleNotFoundError
> Here's my folder structure
>
> features
> ├── environment.py
> ├── signup.feature
> └── steps
>     └── step_signup.py
> radish
> ├── step_signup.py
> └── terrain.py
> util
> └── __init__.py
>
> I import it with:
> `from util import wait_for_element`
>
> It worked for me with behave, but not radish.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/radish-bdd/radish/issues/184


-- Timo Furrer <tuxtimo@gmail.com> (https://tuxtimo.me)

**Comment by timofurrer** [comment]
Thanks for the report. 

The problem here is that the local `util` package isn't part of your import path. 
Simplified this means, that it's neither in `sys.path` nor in `PYTHONPATH`. 

I'm not sure about behave but they probably add the current directory to the `sys.path` and that's why it was working with behave but not with radish. 

To make it work just set the `PYTHONPATH` env variable to the `cwd`: 

```
PYTHONPATH=. radish features/signup.feature
```

Can you verify this? If needed I can upload an example.

**Comment by tangorboyz** [comment]
OK, it worked. Should radish have the same feature as behave? I mean I don't have to specify `PYTHONPATH`, on each run.

**Comment by timofurrer** [comment]
I'm not sure about this. You don't always want to have that. In addition modifying `PYTHONPATH` is considered bad practice.

My question would be:
In situation where you don't want to have the `PYTHONPATH` set - how do you unset it? Let radish know via command line option?

**Comment by timofurrer** [comment]
I don't think I'll implement this right now, unless there are other people who want too. 

Thanks for the input though! :beers:
