### ISSUE TITLE
Add support to stop testing the whole process in the middle of a scenario

### ISSUE THREAD

**Issue by SamuelYvon** [radish-bdd/radish#57]
## The problem

Sometimes, a user might want to stop a feature test in the middle of a scenario. It would be nice to have some sort of exception that can be thrown that would stop the whole testing, and make it so the next scenarios are not tested.

Currently, if I have a .feature like this:

Feature

- Scenario 1
    - Step 1
    - Step 2
    - Step 3
- Scenario 2
    - Step 1
    - Step 2
    - Step 3
- Scenario 3
    - Step 1
    - Step 2
    - Step 3

If I have an exception at Scenario 2, step 2 for example, I might not want to test for scenario 3, because either I know it is gonna fail, or I don't want to 
test for it because I don't trust the results if S2.2 failed.

## My suggestion

I suggest that some sort of check exception could be raised in a step file (like TerminationException). That exception would be catched by the runner and would stop the process and display an appropriate message.

**Comment by SamuelYvon** [comment]
I don't mind taking care of this, but I want to make sure it is _ok_ if I do so. Maybe there is already a way to do this and I am not aware?

**Comment by timofurrer** [comment]
I'm still not entirely sure about the exact use-case for this feature. Can you make a concrete example of when a user might want to use this?

I see two high-level use-cases here:

1. The Scenarios are completely independent from each other, thus, if one Scenario fails you can still run the others without having any unexpected side effects.
2. You know that a failed Scenario will make the subsequent Scenarios to fail (the depend in one way or the other upon each other).

For the first use-case no special action from user has to be taken. 

For the second use-case you should use [the early-exit feature](http://radish.readthedocs.io/en/latest/commandline.html#run-early-exit) provided by radish which will abort the test run upon the first failed Step.

I think adding a checked exception like you suggested would be confusing if you are using those Step implementation as a black box - if you don't specify `-e` you'd expect the test run to just continue. If this would lead to problems (because you have Scenarios with dependencies) you would notice that and use `-e` the next time.

**Comment by timofurrer** [comment]
> I might allow a couples of steps to fail, but some specific steps "need" to make the whole feature test stop.

Thus, this exception would only make radish to stop running the *current feature*? The other features in the test run will run a expected?

**Comment by SamuelYvon** [comment]
That is the goal yes, I think keeping a logical separation between features is important.

**Comment by timofurrer** [comment]
Okay, I see - seems like a legit use-case.

Those conditions - when the feature has to be aborted because it wouldn't make any sense to run the other Scenarios - aren't those actually Pre-Conditions for a Scenario? Wouldn't it be better to have those in the hooks? Or finally implement *Background*s ?

**Comment by timofurrer** [comment]
I'm btw. talking about this [Background Scenario Feature](https://github.com/cucumber/cucumber/wiki/Background) which is currently missing in radish and I wanted to implemented for a looong time. 

So, that might solve our problem in regard to check if a precondition (e.g. network connection) is fulfilled:

```gherkin
Feature: Test DB
    Background:
        Given the connection to the database is established

     Scenario: Add user
         ...

     Scenario: Do some DB queries
        ...
```

So, this would check for the database connection before *each* Scenario in this Feature - if the connection is not available *each* Scenario in this Feature would fail.

The main problem I see about your proposed implementation is that the Scenarios **must** be run in the correct order. I believe one of the basic things about good tests is the independence they need to have. With the *Background* approach this is still given and the execution sequence doesn't matter.

What do you think?

**Comment by SamuelYvon** [comment]
Yeah that's a very good idea. I always make sure my scenarios are ran in order, but this is a fantastic addition. 

I think this would work for me!

**Comment by timofurrer** [comment]
See #59 for the ongoing implementation of the *Background* feature :beers:
