### ISSUE TITLE
Move default radish dir under feature dir

### ISSUE THREAD

**Issue by sschelm** [radish-bdd/radish#81]
It would be a good idea in my opinion to collect all test related files under one subfolder (i.e. `features`) of the project instead of two (`features` and `radish`).

This should be fixed by changing the default path and/or directory of the `radish` folder.

I consider this a potential enhancement.

**Comment by timofurrer** [comment]
In all the situations I've been in / and I projects I worked for always had different folders for the features and the step/terrain implementations. Most of the time this was due to the fact that different people worked on the features (testers, QA) as on the step implementations (developers, testers).

Sometimes you have the step-implementations installed somewhere on your system, too.

However, this is about finding an appropriate default which should fit most people as is. - thus, I'm not sure what's best at the moment. 

I need to think about it - if you have any more pros for your suggestions please write them up!

:beers:

**Comment by timofurrer** [comment]
IMO it still think the current default is best. 

@sschelm anything from your side?

If not I'm going to close this.

**Comment by timofurrer** [comment]
I'm closing it. I'll reopen this issue if necessary.
